### ISSUE TITLE
过渡动画太难受了

### ISSUE THREAD

**Issue by SoyaLeaf** [TaRGroup/CoolApk-Console#13]
过渡时间太长，动作太大。

**Comment by SoyaLeaf** [comment]
另外，能让我加入这个项目么...我的邮箱是597232656@qq.com

**Comment by duangsuse** [comment]
请见 #7 🌝 
另外现在你就可以参加进来
[fork this repo](https://github.com/TaRGroup/CoolApk-Console/fork)

**Comment by SoyaLeaf** [comment]
不只是启动页动画。。。里面的过渡动画也不够自然。
 Nokia6 android 7.1.1 不知道是不是机型原因。。。
