### ISSUE TITLE
求google-services.json

### ISSUE THREAD

**Issue by duangsuse** [TaRGroup/CoolApk-Console#3]
😨rt.刚才上stackoverflow看了,需要google开发者账户。
然而没钱买😭
一般这个文件都是源提供的
特来此求

**Comment by Rachel030219** [comment]
这个…放在 GitHub 上不太好…有滥用风险…

**Comment by Rachel030219** [comment]
顺便，繁中翻译多出三个 values 文件夹，特此差评。为什么不保留一个唯一可用的呢？

**Comment by duangsuse** [comment]
这是找到最好的方法了
我注意到代码里没有如*翻译管理器*这样的东西
所以用的应该是android内建的翻译方法
我参考的是这篇博客http://m.blog.csdn.net/article/details?id=46943931
三个values分别对应英文，中文简体，中文繁体。`不多余`，经AS设计器检查没有发现问题。

**Comment by Trumeet** [comment]
不需要付款的。你去Google统计那里看下就好

**Comment by Trumeet** [comment]
付款只是注册GooglePlay开发者账号（

**Comment by Rachel030219** [comment]
Reopen 差评 @liangyuteng0927
