### ISSUE TITLE
请把/app/src/main/res多余的繁体翻译文件夹删掉

### ISSUE THREAD

**Issue by duangsuse** [TaRGroup/CoolApk-Console#4]
看到了 @Rachel030219 的差评以后我专门到资源目录下看了一下
发现果然有3个繁体的翻译文件夹.......
其中生效的应是values-zh-rTW
为了保证项目可以正常编译请删掉多余的翻译
对这次失误深感抱歉😫
本地的版本库是正常的，估计是commit时没注意，把之前的改动也stage了。

**Comment by Trumeet** [comment]
Rachel今天已经删掉了，谢谢
