### ISSUE TITLE
.SplashActivity的动画时间太长了

### ISSUE THREAD

**Issue by duangsuse** [TaRGroup/CoolApk-Console#7]
启动页面动画放辣么长时间感觉很复古(之前跟trumeet说了，他说改过，Rachel又改回来了),恳请Rachel下次提交时那个动画时间缩短一点，太长既不好看又浪费时间。

**Comment by Rachel030219** [comment]
太短更不好看…我之前测试 Trumeet 的动画，700毫秒甚至在我的手机上还没有完全加载就已经跳转了，所以才设置成 1200 + 2000 ，太快的话至少我个人受不了…即使是现在这种速度，也会卡到从 0.4 到 1.0 ，我实在不敢再想象 700 ms 的效果了…

**Comment by Rachel030219** [comment]
动画时间肯定要至少长于 1000 ms 的（
要不就会出现那种一闪而过的卡顿
不过后期的跳转时间（动画加载完之后还没进 Main 进度条转圈圈的时间）可以稍微缩短一点到同样 1000 ms 左右（只要你们网速够快）

**Comment by Rachel030219** [comment]
我这边即使是加载 developer.coolapk.com 都要将近 800 ms …然后还得 fetch 登录状态…

**Comment by Rachel030219** [comment]
（还有我下次 commit 一定要把 Splash 的进度条删了要不就改成 Horizontal 不然太丑

**Comment by Trumeet** [comment]
加个背景的变色吧，放大过程中逐步变成白色会好一些 @Rachel030219

**Comment by Trumeet** [comment]
要不..加个禁用动画..的？

**Comment by duangsuse** [comment]
@liangyuteng0927 `支持。`那就在设置里加个给用户**自己选择动画速度**的选项吧，这样应该就能选出最好的视觉效果。:heart:

**Comment by Rachel030219** [comment]
作为做动画的我可能会死
人生重来算了.png

**Comment by Rachel030219** [comment]
还不如要么禁用 Splash 要么看 1s 动画（

**Comment by Rachel030219** [comment]
呸不是禁用 Splash 是禁用前面放大的动画

**Comment by duangsuse** [comment]
😂你们私聊吧，我关问题了。
