### ISSUE TITLE
I designed this icon for your app.

### ISSUE THREAD

**Issue by ArchibaldLiu** [TaRGroup/CoolApk-Console#9]
![coolapk_console](https://cloud.githubusercontent.com/assets/25544634/24601897/356344f8-188d-11e7-8b91-6c7ca90b1ebd.png)

**Comment by Trumeet** [comment]
感谢！很快会加入。thx~

**Comment by Trumeet** [comment]
已加入！
[查看Commit](https://github.com/TaRGroup/CoolApk-Console/commit/21ec4c1fb82081f6bb090df2d48a179f0c1682af)
@ArchibaldLiu
